name: Deploy to Dev-Test Channel

on:
  push:
    branches:
      - dev-test # dev-testブランチへのpushをトリガーにする

jobs:
  build_and_preview:
    if: '${{ github.event.repository.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Node.jsのセットアップ
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # 依存関係のインストール
      - name: Install Dependencies
        run: npm ci

      # ビルド実行 (Astro -> dist)
      - name: Build
        run: npm run build

      # Firebase Hosting へのデプロイ (プレビューチャンネル)
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_JUUTEION_WEB }}' # ★ここを修正！
          channelId: 'dev-test'
          projectId: 'juuteion-lp'
          expires: 7d