name: Deploy to Dev-Test Channel

on:
  push:
    branches:
      - dev-test

jobs:
  build_and_preview:
    if: '${{ github.event.repository.full_name == github.repository }}'
    runs-on: ubuntu-latest
    
    # ▼ 追加 1: 全体の作業ディレクトリを juuteion-hub に指定
    defaults:
      run:
        working-directory: ./juuteion-hub

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: './juuteion-hub/package-lock.json' # キャッシュパスも修正（念のため）

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_JUUTEION_WEB }}' # ※ここはあなたのIDのままにしてください
          channelId: 'dev-test'
          projectId: 'juuteion-lp'
          expires: 7d
          entryPoint: ./juuteion-hub # ▼ 追加 2: Firebaseの設定ファイルの場所を指定